export const CONFIG = {
  CLIENT_ID: process.env.NEXT_PUBLIC_CLIENT_ID,
  AUTH_SERVER_URL: process.env.NEXT_PUBLIC_AUTH_SERVER_URL,
  CALLBACK_URL: process.env.NEXT_PUBLIC_CALLBACK_URL,
  SCOPES: process.env.NEXT_PUBLIC_SCOPES,
  CLIENT_SECRET: process.env.CLIENT_SECRET
};